CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), email text UNIQUE NOT NULL, display_name text, locale text DEFAULT 'ar', created_at timestamptz DEFAULT now());
CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE NOT NULL);
CREATE TABLE user_roles (user_id uuid REFERENCES users(id) ON DELETE CASCADE, role_id uuid REFERENCES roles(id) ON DELETE CASCADE, PRIMARY KEY(user_id,role_id));
CREATE TABLE projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), name text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE missions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), name text NOT NULL, status text DEFAULT 'draft', starts_at timestamptz, ends_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE cases (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id), mission_id uuid REFERENCES missions(id), title text NOT NULL, status text DEFAULT 'active', classification text, created_at timestamptz DEFAULT now());
CREATE TABLE aois (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), name text NOT NULL, geometry geometry(Geometry,4326) NOT NULL, properties jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE INDEX aois_geom_idx ON aois USING GIST(geometry);
CREATE TABLE data_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, source_type text NOT NULL, health text DEFAULT 'unknown', last_sync_at timestamptz, metadata jsonb DEFAULT '{}');
CREATE TABLE datasets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id uuid REFERENCES data_sources(id), name text NOT NULL, dataset_type text, acquired_at timestamptz, uri text, metadata jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE TABLE observations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dataset_id uuid REFERENCES datasets(id), case_id uuid REFERENCES cases(id), observed_at timestamptz NOT NULL, geometry geometry(Geometry,4326), properties jsonb DEFAULT '{}');
CREATE INDEX observations_geom_idx ON observations USING GIST(geometry);
CREATE TABLE detections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), observation_id uuid REFERENCES observations(id), model_name text, model_version text, label text, confidence numeric, geometry geometry(Geometry,4326), properties jsonb DEFAULT '{}');
CREATE TABLE alerts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), alert_type text NOT NULL, severity text, confidence numeric, geometry geometry(Geometry,4326), status text DEFAULT 'new', reason text, created_at timestamptz DEFAULT now());
CREATE TABLE evidence (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), dataset_id uuid REFERENCES datasets(id), title text NOT NULL, evidence_type text, geometry geometry(Geometry,4326), observed_at timestamptz, reliability numeric, metadata jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE TABLE findings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), title text NOT NULL, statement text NOT NULL, confidence numeric, status text DEFAULT 'draft', created_at timestamptz DEFAULT now());
CREATE TABLE finding_evidence (finding_id uuid REFERENCES findings(id) ON DELETE CASCADE, evidence_id uuid REFERENCES evidence(id) ON DELETE CASCADE, relation text CHECK (relation IN ('supports','contradicts','context')), PRIMARY KEY(finding_id,evidence_id));
CREATE TABLE hypotheses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), title text NOT NULL, statement text NOT NULL, status text DEFAULT 'open', created_at timestamptz DEFAULT now());
CREATE TABLE reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), template text NOT NULL, language text DEFAULT 'ar', title text NOT NULL, status text DEFAULT 'draft', created_at timestamptz DEFAULT now());
CREATE TABLE products (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_id uuid REFERENCES reports(id), product_type text NOT NULL, status text DEFAULT 'draft', created_at timestamptz DEFAULT now());
CREATE TABLE product_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid REFERENCES products(id) ON DELETE CASCADE, version_no integer NOT NULL, content jsonb NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(product_id,version_no));
CREATE TABLE qc_checks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid REFERENCES products(id), domain text NOT NULL, rule_key text NOT NULL, status text CHECK(status IN ('passed','warning','failed')), message text, created_at timestamptz DEFAULT now());
CREATE TABLE approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), product_id uuid REFERENCES products(id), stage text NOT NULL, reviewer_id uuid REFERENCES users(id), decision text, notes text, decided_at timestamptz);
CREATE TABLE ai_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid REFERENCES cases(id), capability text NOT NULL, model text, input_refs jsonb DEFAULT '[]', output jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE audit_logs (id bigserial PRIMARY KEY, organization_id uuid REFERENCES organizations(id), user_id uuid REFERENCES users(id), action text NOT NULL, entity_type text, entity_id text, details jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE TABLE backups (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), status text NOT NULL, storage_uri text, created_at timestamptz DEFAULT now(), completed_at timestamptz);
